services:
  otrsdb:
    image: ${MYSQL_OTRS_DOCKER_IMAGE}
    container_name: ${MYSQL_OTRS_CONTAINER_NAME}
    build:
      context: ./otrs-mysql-dockerfile
    networks:
      - otrs-network
    env_file:
      - ./.otrsdb-env
    volumes:
      - br.albatross.otrsdb-vol:/var/lib/mysql

  otrsdb_textos_prontos:
    image: ${MYSQL_OTRS_TEXTOS_PRONTOS_DOCKER_IMAGE}
    container_name: ${MYSQL_OTRS_TEXTOS_PRONTOS_CONTAINER_NAME}
    build:
      context: ./otrs-textos-prontos-mysql-dockerfile
    networks:
      - otrs-network
    env_file:
      - ./.otrsdb_textos_prontos-env
    volumes:
      - br.albatross.otrsdb.textos_prontos-vol:/var/lib/mysql

  otrs-app:
    image: ${OTRS_APP_DOCKER_IMAGE}
    container_name: ${OTRS_APP_CONTAINER_NAME}
    build:
      context: ./otrs-wildfly-docker
      args:
        - MYSQL_OTRS_CONTAINER_NAME=${MYSQL_OTRS_CONTAINER_NAME}
        - MYSQL_OTRS_TEXTOS_PRONTOS_CONTAINER_NAME=${MYSQL_OTRS_TEXTOS_PRONTOS_CONTAINER_NAME}
        - MYSQL_OTRS_USER=${MYSQL_OTRS_USER}
        - MYSQL_OTRS_PASSWORD=${MYSQL_OTRS_PASSWORD}
        - MYSQL_OTRS_DATABASE=${MYSQL_OTRS_DATABASE}
        - MYSQL_OTRS_DATABASE_HOST=${MYSQL_OTRS_DATABASE_HOST}

        - MYSQL_OTRS_TEXTOS_PRONTOS_USER=${MYSQL_OTRS_TEXTOS_PRONTOS_USER}
        - MYSQL_OTRS_TEXTOS_PRONTOS_PASSWORD=${MYSQL_OTRS_TEXTOS_PRONTOS_PASSWORD}
        - MYSQL_OTRS_TEXTOS_PRONTOS_DATABASE_HOST=${MYSQL_OTRS_TEXTOS_PRONTOS_DATABASE_HOST}
        - MYSQL_OTRS_TEXTOS_PRONTOS_DATABASE=${MYSQL_OTRS_TEXTOS_PRONTOS_DATABASE}

    networks:
      - otrs-network
    depends_on:
      otrsdb:
        condition: service_started
      otrsdb_textos_prontos:
        condition: service_started
    ports:
      - 8080:8080

networks:
  otrs-network:
    name: ${OTRS_NETWORK_NAME}
    driver: bridge

volumes:
  br.albatross.otrsdb-vol:
  br.albatross.otrsdb.textos_prontos-vol:
